server:
  port: 7788 
#mysql相关配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动
    url: jdbc:mysql://localhost:3306/db_spring?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource #使用druid连接池
#    schema: #用来运行sql#    - classpath:sql/tb_use2.sql