server:
  port: 7014 
spring:
  application:    name: myheart-install
#eureka客户端
eureka:                                                     
  client:   #客户端注册进eureka服务列表                                                
    serviceUrl:     #这里填写的是服务注册中心地址
      defaultZone: http://localhost:7001/eureka/ #单机版
  instance:
    instance-id: myheart-install7014       #自定义服务名称信息   
    prefer-ip-address: true   #访问路径可以显示ip地址